### ISSUE TITLE
Blind editing

### ISSUE THREAD

**Issue by mtbadakhshan** [shahinism/python-negar#17]
This spell corrector split all 'ها's and 'می's in any words. In some cases it causes mistake. i.e.:
شهادت -> ش‌هادت
میلیارد -> می‌لیارد
میلیون -> می‌لیون
حمید -> حمی‌د

**Comment by shahinism** [comment]
Hi, 
Thanks for reporting this issue. Unfortunately, I don't have enough time to spend on this project. But if you are interested, please feel free to submit pull requests :blush:
