### ISSUE TITLE
pypi issue with python-negar

### ISSUE THREAD

**Issue by javadr** [shahinism/python-negar#22]
Dear @shahinism  and @Alir3z4

It seems you  have used the `python-negar` name in the past, and whenever I tried to upload it with this name I got the following error:
```
WARNING  Error during upload. Retry with the --verbose option for more details.                                                         
WARNING:twine.utils:Error during upload. Retry with the --verbose option for more details.
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/                                                                  
         Invalid or non-existent authentication information. See https://pypi.org/help/#invalid-auth for more information.              
ERROR:twine.__main__:HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
Invalid or non-existent authentication information. See https://pypi.org/help/#invalid-auth for more information.
```

I tried the `test.pypi.org` and it worked.
Could you add me to the project to upload the updates to the `PyPI`?
It's really annoying to have not the package via `pip`. 

Best, Javad

**Comment by Alir3z4** [comment]
Hey

Thanks for working on the project.
@shahinism was set as Maintainer on it, but just now I changed it to Owner.

As he's the owner and author of the project, it's up to him to issue access for you.

@shahinism both of us are Owner on the package, feel free to remove my access as I never had the chance to continue working on this project.

**Comment by javadr** [comment]
Thanks for your fast reply and I really appreciate your work on this project in the past. 
I hope I could make it better with extra features.

**Comment by shahinism** [comment]
Thanks @Alir3z4 for the help.

@javadr would you please let me know what is your username on PyPI?

**Comment by javadr** [comment]
Thanks @shahinism. My id is the same there.

**Comment by shahinism** [comment]
Invited you as a maintainer.

**Comment by shahinism** [comment]
@javadr you should have that one as well now.

**Comment by javadr** [comment]
Thanks a million. 
I've uploaded the last version. Now it is available via PyPI. :smile:
