### ISSUE TITLE
Bug Report: Error in Suffix Separating Feature

### ISSUE THREAD

**Issue by MahtaFetrat** [shahinism/python-negar#24]
#### Description
When the suffix separating feature is not turned off, some words that have a plural suffix as a part of them are edited wrong. For example `نهایی` is edited to `ن‌هایی`.

#### Steps to Reproduce

```python
from negar.virastar import PersianEditor
edited_text = PersianEditor('مقصد نهایی').text
print(edited_text)
```

**Comment by javadr** [comment]
First, I would like to sincerely thank you for taking the time to report this issue.

Secondly, the reason this issue remained unaddressed was that I did not receive a notification about it. I only came across it by chance yesterday.

Please get the latest version.

In such cases, you can usually resolve the problem by adding your words to the list of immutable words. Using Negar-GUI makes managing this list straightforward and efficient.
