### ISSUE TITLE
Remove GUI part

### ISSUE THREAD

**Issue by Alir3z4** [shahinism/python-negar#7]
- [x] Removing Screenshot directory from repo.
- [x] Remove https://github.com/shahinism/python-negar/blob/master/negar/gui.py from repo.
- [x] Initial separate project like **negar-gui**.

**Comment by javadr** [comment]
Dear @shahinism, 

Would you mind if I move the `GUI` part to the new repo[1], and make the `python-negar` just for the main class? As you know some of my commits to this project were around `GUI` improvement, not the virastar` class. 

Best, Javad

[1] Something like `negar-gui` under my git account.

**Comment by shahinism** [comment]
@javadr Yes, sounds like a good idea. The GUI never was mature, now that you are working on it, probably better to keep it separated.

**Comment by javadr** [comment]
Thanks for your support. 

Now the `GUI` moved to [`negar-gui`](HTTP://github.com/javadr/negar-gui) repo and will get some update in near future, I hope. It is also accessible via [PyPi](https://pypi.org/project/negar-gui/). 

Would you like to add you both (@shahinism  @Alir3z4) to this repo as maintainers?
